### ISSUE TITLE
Error: QeRAwzTK: Chunk reference error for type 2

### ISSUE THREAD

**Issue by anjojohn** [iizukanao/node-rtsp-rtmp-server#90]
Streaming with Gstreamer rtmpsink. 
error log below

```
/home/ubuntu/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: QeRAwzTK: Chunk reference error for type 2: previous chunk for id 29 is not found (possibly a bug)
    at RTMPSession.parseRTMPMessages (/home/ubuntu/node-rtsp-rtmp-server/rtmp.js:1356:19)
    at /home/ubuntu/node-rtsp-rtmp-server/rtmp.js:2358:33
    at RTMPSession.handleData (/home/ubuntu/node-rtsp-rtmp-server/rtmp.js:2581:16)
    at Socket.<anonymous> (/home/ubuntu/node-rtsp-rtmp-server/rtmp.js:2642:34)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by iizukanao** [comment]
@anjojohn Thank you for letting me know! This bug has now been fixed in the master branch.

**Comment by ozankonur** [comment]
I am still getting this error. For first connection there is no bug. After second connection this bug occurs again;

Error: IBcxImB7: Chunk reference error for type 2: previous chunk for id 33 is not found (possibly a bug)
  at RTMPSession.parseRTMPMessages (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:1316:21)
  at /home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2497:24
  at Sequent.callback (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2515:11)
  at Sequent.done (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/node_modules/sequent/lib/sequent.js:151:34)
  at /home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2674:19
  at RTMPSession.handleData (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2676:7)
  at Socket.<anonymous> (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2711:23)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)

**Comment by ozankonur** [comment]
++ this;

/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/server.coffee:46
    throw err;
    ^

Error: UVSofQ7o: Chunk reference error for type 3: previous chunk for id 57 is not found (possibly a bug)
  at RTMPSession.parseRTMPMessages (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:1329:21)
  at /home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2497:24
  at RTMPSession.handleData (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2676:7)
  at Socket.<anonymous> (/home/nodeRTMP2RTSP/node-rtsp-rtmp-server/rtmp.coffee:2711:23)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
